### ISSUE TITLE
[LDAP] Pending enhancements

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy-analyzers#58]
A few things pending still for the LDAP analyzer, waiting for other tickets:

- [ ] Once &convert is fixed for unit types with parameters, we can apply it to more types. (https://github.com/zeek/spicy/issues/917)
- [ ]  Once we have `Undef` Zeek-side, use it to replace the `NOT_SET` fields (https://github.com/zeek/spicy-plugin/issues/35)
- [ ]  Once we have switch-level `&parse-from`, use that instead of one per case (https://github.com/zeek/spicy/issues/913)
